CREATE TABLE IF NOT EXISTS acms_cycle (
    cycle_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    dataset_ts DATETIME NOT NULL,
    generated_at DATETIME NOT NULL,
    pipeline_version VARCHAR(50),
    dataset_hash CHAR(64),
    dataset_path VARCHAR(255),
    market_session VARCHAR(50),
    regime_label VARCHAR(50),
    regime_score DECIMAL(6,2),
    cio_posture VARCHAR(50),
    confidence DECIMAL(6,4),
    vix DECIMAL(10,4),
    fear_greed DECIMAL(10,4),
    fear_greed_status VARCHAR(50),
    usd_jpy DECIMAL(12,4),
    uup_return DECIMAL(10,4),
    spy_return DECIMAL(10,4),
    qqq_return DECIMAL(10,4),
    iwm_return DECIMAL(10,4),
    total_assets DECIMAL(18,4),
    cash_value DECIMAL(18,4),
    cash_weight DECIMAL(10,4),
    market_value DECIMAL(18,4),
    total_pnl DECIMAL(18,4),
    cash_fortress_mode BOOLEAN DEFAULT FALSE,
    scout_mode BOOLEAN DEFAULT FALSE,
    second_tranche_status VARCHAR(50),
    scale_in_status VARCHAR(50),
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    llm_order_generation_enabled BOOLEAN DEFAULT FALSE,
    system_generated_orders INT DEFAULT 0,
    data_integrity_status VARCHAR(50),
    pnl_integrity_status VARCHAR(50),
    blocked_actions_json JSON,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_acms_cycle_ts (dataset_ts),
    INDEX idx_acms_cycle_regime (regime_label)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_ticker_cycle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    ticker VARCHAR(20) NOT NULL,
    company_name VARCHAR(255),
    theme VARCHAR(100),
    sleeve VARCHAR(50),
    price DECIMAL(18,4),
    day_return DECIMAL(10,4),
    volume BIGINT,
    volume_zscore DECIMAL(10,4),
    flow_bias VARCHAR(30),
    main_net_flow DECIMAL(20,4),
    super_large_net_flow DECIMAL(20,4),
    large_net_flow DECIMAL(20,4),
    medium_net_flow DECIMAL(20,4),
    small_net_flow DECIMAL(20,4),
    in_flow DECIMAL(20,4),
    options_bias VARCHAR(30),
    put_call_ratio DECIMAL(10,4),
    hedge_demand_score DECIMAL(10,4),
    price_direction VARCHAR(30),
    flow_direction VARCHAR(30),
    causal_status VARCHAR(50),
    acms_state VARCHAR(80),
    secondary_state VARCHAR(80),
    acms_confidence DECIMAL(6,4),
    cio_meaning VARCHAR(255),
    recommended_posture VARCHAR(50),
    blocked_actions_json JSON,
    data_quality_flag VARCHAR(50),
    raw_fields_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_ticker_cycle (ticker, cycle_id),
    INDEX idx_acms_ticker_flow (flow_bias),
    INDEX idx_acms_ticker_state (acms_state),
    INDEX idx_acms_ticker_theme (theme)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_theme_cycle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    theme VARCHAR(100) NOT NULL,
    theme_direction VARCHAR(50),
    avg_move DECIMAL(10,4),
    positive_count INT,
    total_count INT,
    dominant_flow_bias VARCHAR(30),
    net_main_flow DECIMAL(20,4),
    causal_status VARCHAR(50),
    acms_state VARCHAR(80),
    confidence DECIMAL(6,4),
    cio_posture VARCHAR(50),
    notes TEXT,
    raw_theme_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_theme_cycle (theme, cycle_id),
    INDEX idx_acms_theme_state (acms_state)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_forecast (
    forecast_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    forecast_time DATETIME NOT NULL,
    scope_type VARCHAR(30),
    scope_id VARCHAR(100),
    forecast_question TEXT NOT NULL,
    forecast_probability DECIMAL(6,4) NOT NULL,
    confidence DECIMAL(6,4),
    horizon_sessions INT,
    horizon_end_time DATETIME,
    outcome_definition TEXT,
    regime_label VARCHAR(50),
    acms_state VARCHAR(80),
    cio_posture VARCHAR(50),
    benchmark_type VARCHAR(50),
    status VARCHAR(30) DEFAULT 'OPEN',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_forecast_status (status),
    INDEX idx_acms_forecast_scope (scope_type, scope_id),
    INDEX idx_acms_forecast_time (forecast_time)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_outcome (
    outcome_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    forecast_id BIGINT,
    cycle_id BIGINT,
    resolved_at DATETIME NOT NULL,
    outcome_binary BOOLEAN,
    outcome_value DECIMAL(18,6),
    forward_return_1s DECIMAL(10,4),
    forward_return_3s DECIMAL(10,4),
    forward_return_5s DECIMAL(10,4),
    forward_return_10s DECIMAL(10,4),
    forward_return_20s DECIMAL(10,4),
    spy_relative_return DECIMAL(10,4),
    qqq_relative_return DECIMAL(10,4),
    sector_relative_return DECIMAL(10,4),
    max_adverse_excursion DECIMAL(10,4),
    max_favorable_excursion DECIMAL(10,4),
    brier_score DECIMAL(10,6),
    log_loss DECIMAL(10,6),
    outcome_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (forecast_id) REFERENCES acms_forecast(forecast_id),
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_outcome_forecast (forecast_id),
    INDEX idx_acms_outcome_resolved (resolved_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_decision (
    decision_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    decision_time DATETIME NOT NULL,
    decision_type VARCHAR(50),
    ticker VARCHAR(20),
    theme VARCHAR(100),
    acms_state VARCHAR(80),
    regime_label VARCHAR(50),
    cio_posture VARCHAR(50),
    action_taken TEXT,
    action_avoided TEXT,
    reason TEXT,
    trigger_condition TEXT,
    kill_condition TEXT,
    review_due_time DATETIME,
    cash_weight_before DECIMAL(10,4),
    cash_weight_after DECIMAL(10,4),
    hedge_status VARCHAR(50),
    decision_quality_class VARCHAR(80) DEFAULT 'PENDING_REVIEW',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_decision_time (decision_time),
    INDEX idx_acms_decision_ticker (ticker),
    INDEX idx_acms_decision_quality (decision_quality_class)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_agent_cycle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    agent_name VARCHAR(100) NOT NULL,
    agent_role VARCHAR(100),
    model_version VARCHAR(100),
    prompt_version VARCHAR(100),
    recommendation VARCHAR(100),
    confidence DECIMAL(6,4),
    acms_layer_focus VARCHAR(80),
    acms_state_claim VARCHAR(80),
    dissent_flag BOOLEAN DEFAULT FALSE,
    dissent_reason TEXT,
    accepted_by_chief_strategist BOOLEAN,
    overridden_by_chief_strategist BOOLEAN,
    outcome_correct BOOLEAN,
    agent_brier_score DECIMAL(10,6),
    false_positive_flag BOOLEAN,
    false_negative_flag BOOLEAN,
    overclaiming_flag BOOLEAN,
    summary TEXT,
    raw_output_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_agent_cycle (agent_name, cycle_id),
    INDEX idx_acms_agent_dissent (dissent_flag)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_data_quality_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    issue_time DATETIME NOT NULL,
    issue_type VARCHAR(80),
    severity VARCHAR(30),
    affected_ticker VARCHAR(20),
    affected_theme VARCHAR(100),
    affected_component VARCHAR(100),
    issue_description TEXT,
    detected_by VARCHAR(100),
    resolved BOOLEAN DEFAULT FALSE,
    resolved_at DATETIME,
    resolution_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cycle_id) REFERENCES acms_cycle(cycle_id),
    INDEX idx_acms_dq_cycle (cycle_id),
    INDEX idx_acms_dq_type (issue_type),
    INDEX idx_acms_dq_resolved (resolved)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_signal_entropy (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    ticker VARCHAR(20) NOT NULL,
    old_label VARCHAR(80),
    signal_entropy_raw DECIMAL(12,6),
    signal_entropy_normalized DECIMAL(12,6),
    evidence_category_count INT,
    clean_signal_weight DECIMAL(18,6),
    dirty_signal_weight DECIMAL(18,6),
    source_tier_weighted_entropy DECIMAL(12,6),
    classification VARCHAR(80),
    evidence_categories_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_entropy_ticker (ticker),
    INDEX idx_str_entropy_run (run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_source_capacity (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    source_name VARCHAR(120) NOT NULL,
    source_tier INT,
    signal_count INT,
    confirmed_count INT,
    contradicted_count INT,
    unresolved_count INT,
    estimated_mutual_information DECIMAL(12,6),
    estimated_channel_capacity DECIMAL(12,6),
    capacity_confidence VARCHAR(80),
    tier_upgrade_candidate BOOLEAN DEFAULT FALSE,
    tier_downgrade_candidate BOOLEAN DEFAULT FALSE,
    status VARCHAR(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_source_name (source_name),
    INDEX idx_str_source_run (run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_cost_basis_reconciliation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    ticker VARCHAR(20) NOT NULL,
    broker_unrealized DECIMAL(18,4),
    computed_unrealized DECIMAL(18,4),
    third_witness_unrealized DECIMAL(18,4),
    delta_broker_vs_computed DECIMAL(18,4),
    delta_broker_vs_third DECIMAL(18,4),
    delta_computed_vs_third DECIMAL(18,4),
    selected_source VARCHAR(80),
    resolution_status VARCHAR(100),
    source_reliability_update VARCHAR(160),
    cio_review_required BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_cost_basis_ticker (ticker),
    INDEX idx_str_cost_basis_run (run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_kelly_sizing_advisory (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    ticker VARCHAR(20) NOT NULL,
    edge_estimate DECIMAL(12,6),
    full_kelly_fraction DECIMAL(12,6),
    quarter_kelly_fraction DECIMAL(12,6),
    quarter_kelly_usd DECIMAL(18,4),
    capped_advisory_size_usd DECIMAL(18,4),
    current_position_usd DECIMAL(18,4),
    current_vs_advisory_delta DECIMAL(18,4),
    kelly_status VARCHAR(120),
    cio_override_required BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_kelly_ticker (ticker),
    INDEX idx_str_kelly_run (run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_hedge_ratio_review (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    current_hedge_value DECIMAL(18,4),
    current_hedge_pct_of_market_value DECIMAL(12,6),
    implied_full_hedge_value DECIMAL(18,4),
    fractional_hedge_value DECIMAL(18,4),
    hedge_gap_usd DECIMAL(18,4),
    hedge_status VARCHAR(80),
    raw_review_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_hedge_run (run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS acms_str_cycle_summary (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(120) NOT NULL,
    cycle_timestamp DATETIME NOT NULL,
    dataset_timestamp DATETIME NOT NULL,
    report_binding_id VARCHAR(128) NOT NULL,
    governance_pack_id VARCHAR(128) NOT NULL,
    execution_authority VARCHAR(50) DEFAULT 'CIO_ONLY_MANUAL',
    order_routing_enabled BOOLEAN DEFAULT FALSE,
    system_orders_generated INT DEFAULT 0,
    status VARCHAR(80),
    version VARCHAR(50),
    signal_entropy_count INT,
    source_capacity_count INT,
    cost_basis_conflict_count INT,
    kelly_advisory_count INT,
    hedge_status VARCHAR(80),
    brier_logging_status VARCHAR(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_str_summary_run (run_id)
) ENGINE=InnoDB;
